# create ansible user
- src: git+git@github.com:public-ansible-roles/create-ansible-user.git

# configure sshd
- src: git+git@github.com:public-ansible-roles/sshd.git

# Install terraform
- src: git+git@github.com:public-ansible-roles/terraform.git

